name = "Couenne_jll"
uuid = "f09e9e23-9010-5c9e-b679-9f1d8f79b85c"
version = "0.5.8+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
Ipopt_jll = "9cc047cb-c261-5740-88fc-0cf96f7bdcc7"
Cbc_jll = "38041ee0-ae04-5750-a4d2-bb4d0d83d27d"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
ASL_jll = "ae81ac8f-d209-56e5-92de-9978fef736f9"
Bonmin_jll = "29cba6d7-6840-5cf2-a2fa-9bdfccfe29ea"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.2.0"
julia = "1.0"
